In [1]:
#import Numpy
import numpy as np

In [2]:

#Array of 10 Zeros
zero_arr = np.zeros(10)

In [3]:
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Array of 10  Ones
one_arr = np.ones(10)

In [5]:
one_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# Array of 10 fives
five_arr = np.ones(10) * 5

In [7]:
five_arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:

#array from 10 to 50
ints = np.arange(10,51)

In [9]:
ints

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
#matrix from 0 to 8

mat = np.arange(0,9).reshape(3,3)

In [11]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# 3 x 3 identiy matrix

identity = np.eye(3)

In [13]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Generating random number between 0 and 1
np.random.rand()

0.5117756243790305

In [15]:
#Creating array of standard normal distribution numbers
std_arr = np.random.randn(25)

In [16]:
std_arr

array([ 0.15205569,  0.03134768, -0.84128507,  0.30370702, -1.22617299,
        1.67701242,  0.16274053,  0.47331703,  0.76949351, -0.68006297,
       -0.38066545,  0.88472034, -0.54289335, -1.91802648, -1.14621414,
        0.35418542, -0.26000696,  1.83495666,  0.56870029, -0.73830505,
        0.56358734,  1.49850698,  0.34134201,  0.63028216, -0.80111769])

In [17]:
# using linspace

lin_arr = np.linspace(0,1,101)

In [18]:
lin_arr

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [19]:
#using linspace again
lin_arr_2 = np.linspace(0,1,20)

In [20]:
lin_arr_2

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Indexing

In [21]:
mat = np.arange(1,26).reshape(5,5)

In [22]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
#slice out array

mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [25]:
# Return 20

mat[3,4]

20

In [28]:
#slice out 

mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [32]:
#slice out final row
mat[4]

array([21, 22, 23, 24, 25])

In [33]:
#slice out final two row
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Operations

In [34]:
#total sum of mat
mat.sum()

325

In [35]:
# standard deviation of mat
mat.std()

7.211102550927978

In [36]:
#total sum of columns

mat.sum(axis=0)

array([55, 60, 65, 70, 75])